# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7vx485tffg1157-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ishita/Documents/minor_project/final_minor_project/Pipelined/final_minor/final_minor.cache/wt [current_project]
set_property parent.project_path /home/ishita/Documents/minor_project/final_minor_project/Pipelined/final_minor/final_minor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/store_whb.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/signext.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/reg_file.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/PC_Src.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/imm_gen.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/control_unit.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/alu.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/WB.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/MEM_WB.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/MEM.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/IF_ID.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/IF.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/ID_EX.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/ID.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/EX_MEM.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/EX.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/instr_mem.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/data_mem.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/core.v
  /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/top_module.v
}
catch { write_hwdef -file top_module.hwdef }
synth_design -top top_module -part xc7vx485tffg1157-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
