# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-3403-ishita-HP-Laptop-15s-gr0xxx/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx485tffg1157-1

    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/store_whb.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/signext.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/reg_file.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/PC_Src.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/imm_gen.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/control_unit.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/alu.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/WB.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/MEM_WB.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/MEM.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/IF_ID.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/IF.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/ID_EX.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/ID.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/EX_MEM.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/EX.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/instr_mem.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/data_mem.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/core.v
      /home/ishita/Documents/minor_project/final_minor_project/Pipelined/design/top_module.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_module
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-3403-ishita-HP-Laptop-15s-gr0xxx/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
